server:
  port: 80
  servlet:
    context-path: /
  address: 0.0.0.0

# database
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/store?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis: # redis
    port: 6379
    host: 127.0.0.1
    connect-timeout: 10s
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数
        max-wait: 200s #连接池最大阻塞等待时间，默认没有限制
        max-idle: 8 #连接池中最大空闲连接
        min-idle: 0
  security:
    user:
      name: admin
      password: admin


# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

videoFilePath: E:/C/
